let allTerms = [
  'The Mandalorian',
  'Billie Eilish',
  'Baby Yoda',
  'Iran missile',
  'Iran General',
  'Iran Missile',
  'Ukraine Plane Crash',
  'Prince Harry',
  'Meghan Markle',
  'Wuhan',
  'Impeachment',
  'Kobe Bryant',
  'Shakira',
  'Iowa Caucus',
  'Parasite',
  'Ryan Newman',
  'The Weeknd',
  'Pop Smoke',
  'Bernie Sanders',
  'Harvey Weinstein',
  'Stock Market',
  'Super Tuesday',
  'Pandemic',
  'Elizabeth Warren',
  'Coronavirus',
  'Lockdown',
  'Quarantine',
  'Unemployment',
  'Tiger King',
  'Furlough',
  'World Health Organization',
  'Stimulus Check',
  'IRS',
  'Kim Jong Un',
  'UFO',
  'Elon Musk',
  'Ahmaud Arbery',
  'Elon Musk Baby',
  'Murder Hornet',
  'SpaceX',
  'George Floyd',
  'Black Lives Matter',
  'Jeffrey Epstein',
  'Breonna Taylor',
  'Protests',
  'PS5',
  'Juneteenth',
  'Bubba Wallace',
  'Naya Rivera',
  'Kanye West',
  'The Box',
  'Joe Biden',
  'Kamala Harris',
  'beirut',
  'WAP',
  'Fall Guys',
  'Chadwick Boseman',
  'Hurricane Laura',
  'Jacob Blake',
  'Zoom',
  'Among Us',
  'Ruth Bader Ginsburg',
  'Lakers',
  'Eddie Van Halen',
  'Amy Coney Barrett',
  'Borat 2',
  'iPhone 12',
  'Hunter Biden',
  'Cyberpunk 2077',
  'Election Day',
  'Election Results',
  'Xbox X',
  'UFC',
  'Covid Vaccine',
  'Mike Tyson',
  '2021',
  'New Year',
  'Election results',
  'Coronavirus update',
  'Coronavirus symptoms',
  'Who is winning the election',
  'Iran',
  'Australia fires',
  'Tom Hanks',
  'Vanessa Bryant',
  "Chris D'Elia",
  'Jada Pinkett Smith',
  'Timothee Chalamet',
  'Ricky Gervais',
  'Tom Brady',
  'Rudy Gobert',
  'Elon Musk baby',
  'Baby platypus',
  'Ice Age baby',
  'Anderson Cooper baby',
  'Baby Nut',
  'Entanglement',
  'Antebellum',
  'Asymptomatic',
  'Valorant',
  'Genshin Impact',
  'Ghost of Tsushima',
  'Godzilla',
  'GOOBA',
  'Break My Stride',
  'August Alsina',
  'Adele',
  'Doja Cat',
  'Grimes',
  'Covid testing near me',
  'Early voting near me',
  'Fires near me',
  'Voting near me',
  'Protests near me',
  '1917',
  'Black Panther',
  'Harley Quinn',
  'Little Women',
  'Virtual field trips',
  'Virtual museum tours',
  'Virtual Kentucky Derby',
  'Virtual learning',
  'Beirut',
  'Boris Johnson',
  'Pete Buttigieg',
  'Mike Bloomberg',
  'Cobra Kai',
  'Ozark',
  'The Umbrella Academy',
  "The Queen's Gambit",
  'Toilet paper'
];

//  let uniqs = [...new Set(arr)]
//  console.dir(uniqs, {'maxArrayLength': null});


module.exports = {
    allTerms
}